development:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  encoding: unicode
  adapter: postgresql
  username: trip-note
  port: <%= ENV['PORT'] %>
  host: <%= ENV['HOST'] %>
  database: <%= ENV['DATABASE'] %>
  password: <%= ENV['PASSWORD'] %>
